-- MySQL Script generated by MySQL Workbench
-- Fri Dec 27 08:52:55 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customer` (
  `id_customer` INT NOT NULL,
  `no_identitas` VARCHAR(16) NOT NULL,
  `nama` VARCHAR(32) NOT NULL,
  `alamat` VARCHAR(50) NULL DEFAULT CURRENT_TIMESTAMP,
  `telepon` VARCHAR(15) NULL,
  PRIMARY KEY (`id_customer`),
  UNIQUE INDEX `id_customer_UNIQUE` (`id_customer` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`detail_mobil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`detail_mobil` (
  `id_detail_mobil` INT NOT NULL,
  `nomor_mesin` VARCHAR(10) NULL,
  `Merek` VARCHAR(50) NULL,
  `tahun_rakit` YEAR NULL,
  `warna` VARCHAR(30) NULL,
  PRIMARY KEY (`id_detail_mobil`),
  UNIQUE INDEX `id_detail_mobil_UNIQUE` (`id_detail_mobil` ASC) VISIBLE,
  UNIQUE INDEX `nomor_mesin_UNIQUE` (`nomor_mesin` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mobil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mobil` (
  `id_mobil` INT NOT NULL,
  `nama` VARCHAR(30) NOT NULL,
  `nomor_polisi` VARCHAR(5) NULL,
  `harga` INT NULL,
  `id_detail_mobil` INT NOT NULL,
  PRIMARY KEY (`id_mobil`),
  UNIQUE INDEX `nomor_polisi_UNIQUE` (`nomor_polisi` ASC) VISIBLE,
  INDEX `fk_mobil_detail_mobil_idx` (`id_detail_mobil` ASC) VISIBLE,
  CONSTRAINT `fk_mobil_detail_mobil`
    FOREIGN KEY (`id_detail_mobil`)
    REFERENCES `mydb`.`detail_mobil` (`id_detail_mobil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipe_pembayaran`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipe_pembayaran` (
  `id_tipe` INT NOT NULL,
  `nama` VARCHAR(30) NULL,
  `bunga` INT NULL,
  PRIMARY KEY (`id_tipe`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`transaksi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`transaksi` (
  `id_transaksi` INT NOT NULL,
  `tanggal` DATE NULL,
  `lunas` TINYINT NULL,
  `id_tipe_pembayaran` INT NOT NULL,
  `id_customer` INT NOT NULL,
  `id_mobil` INT NOT NULL,
  `total_pembayaran` INT NULL,
  PRIMARY KEY (`id_transaksi`),
  INDEX `fk_transaksi_tipe_pembayaran1_idx` (`id_tipe_pembayaran` ASC) VISIBLE,
  INDEX `fk_transaksi_customer1_idx` (`id_customer` ASC) VISIBLE,
  INDEX `fk_transaksi_mobil1_idx` (`id_mobil` ASC) VISIBLE,
  CONSTRAINT `fk_transaksi_tipe_pembayaran1`
    FOREIGN KEY (`id_tipe_pembayaran`)
    REFERENCES `mydb`.`tipe_pembayaran` (`id_tipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transaksi_customer1`
    FOREIGN KEY (`id_customer`)
    REFERENCES `mydb`.`customer` (`id_customer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transaksi_mobil1`
    FOREIGN KEY (`id_mobil`)
    REFERENCES `mydb`.`mobil` (`id_mobil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
